export interface Company {
  id: number ,
	businessRn: string,
	companyNo: string,
	englishName: string,
	arabicName: string,
	phoneNo: string,
	address: string,
	dateHijri: string,
	dateGregorian: string,
	dateEstablishment: string,
	buildingNo: string,
	englishStreetName: string,
	arabicStreetName: string,
	englishDistrict: string,
	arabicDistrict: string,
	englishCity: string,
	arabicCity: string,
	englishCountry: string,
	arabicCountry: string,
	additionalNo: string,
	postalCode: string,
	secondBusinessId: string,
	secondBusinessIdType: string,
	compayIconLocation80: string,
	compayIconLocationA4: string
}
